spring:
  application:
    name: tefo
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  output:
    ansi:
      enabled: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 10
          batch_versioned_data: true
          fetch_size: 1000
        generate_statistics: true
        dialect: org.hibernate.community.dialect.SQLiteDialect

  datasource:
    url: jdbc:sqlite:/Users/christiansoriani/Desktop/telegramForensic/org.telegram.messenger/files/cache4.db
    driver-class-name: org.sqlite.JDBC

springdoc:
  api-docs:
    path: /api/api-docs-json
    enabled: true
    groups:
      enabled: true
  swagger-ui:
    path: /api/api-docs